services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    env_file:
      - path: .env.example
        required: true
      - path: .env
        required: false
    environment:
      - N8N_PAYLOAD_SIZE_MAX=32
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped
